export const studentChapterOptions = [
  "AAU/ISTH",
  "Abia State University Teaching Hospital - ABSUTH",
  "ABSUTH",
  "ABUTH",
  "Afe Babalola University Teaching Hospital - ABUADTH",
  "Abubakar Tafawa Balewa University Teaching Hospital - ATBUTH",
  "AE-FUTH",
  "Ahmadu Bello University Teaching Hospital - ABUTH",
  "AKTH",
  "Alex Ekwueme University Teaching Hospital - AEFUTH",
  "Aminu Kano University Teaching Hospital - AKTH",
  "Ambrose Alli University/ Irrua Specialist Teaching Hospital - AAU/ISTH",
  "Barau-Dikko University Teaching Hospital - BDTH-KASU",
  "BDTH-KASU",
  "Benue State University Teaching Hospital - BSUTH",
  "Bingham University Teaching Hospital - BHUTH",
  "Bowen University Teaching Hospital - BUTH",
  "Chukwuemeka Odumegwu Ojukwu University Teaching Hospital - COOUTH",
  "Delta State University Teaching Hospital - DELSUTH",
  "EBSUTH",
  "Ebonyi State University Teaching Hospital - EBSUTH",
  "Ekiti State University Teaching Hospital - EKSUTH",
  "Enugu State University Teaching Hospital - ESUTH",
  "FUTH-LAFIA",
  "Gombe State University Teaching Hospital - GSUTH",
  "Gregory University Teaching Hospital - GUTH",
  "GSUTH",
  "GUTH",
  "Igbinedion University Teaching Hospital - IUTH",
  "Imo State University Teaching Hospital - IMSUTH",
  "IMSUTH",
  "Jos University Teaching Hospital - JUTH",
  "JUTH",
  "Lagos State University Teaching Hospital - LASUTH",
  "Lagos University Teaching Hospital - LUTH",
  "LASUTH",
  "Lautech Teaching Hospital - LTH",
  "Niger Delta University Teaching Hospital - NDUTH",
  "Nnamdi Azikiwe University Teaching Hospital - NAUTH",
  "Obafemi Awolowo University Teaching Hospital - OAUTH",
  "Olabisi Onabanjo University Teaching Hospital - OOUTH",
  "Osun State University Teaching Hospital - UNIOSUNTH",
  "RSUTH",
  "UDUTH",
  "University College Hospital - UCH",
  "University of Abuja Teaching Hospital - UATH",
  "University of Benin Teaching Hospital - UBTH",
  "University of Calabar Teaching Hospital - UCTH",
  "University of Ilorin Teaching Hospital - UITH",
  "University of Maiduguri Teaching Hospital - UMTH",
  "University of Medical Sciences Teaching Hospital (UNIMEDTH)",
  "University of Nigeria Teaching Hospital - UNTH",
  "University of Port Harcourt Teaching Hospital - UPTH",
  "University of Uyo Teaching Hospital – UUTH",
  "Usman Dan Fodio University Teaching Hospital - UDUTH",
];

export const doctorsRegionLists = [
  "Abia - Umahia",
  "Adamawa",
  "Akwa Ibom",
  "Anambra (COOUTH)",
  "Anambra (NAUTH)",
  "Bauchi",
  "Bayelsa",
  "Benue",
  "Borno",
  "CMDA Uyo",
  "Cross River",
  "Delta - DELSUTH, Oghara",
  "Delta FMC, Asaba",
  "Ebonyi",
  "Edo-Benin",
  "Edo-SHMB",
  "Edo-Irrua",
  "Ekiti - Ido",
  "Ekiti-Ado",
  "Enugu",
  "FCT Gwagwalada",
  "FCT Municipal",
  "Gombe",
  "Imo",
  "Kaduna - Kaduna",
  "Kaduna - Zaria",
  "Kano",
  "Kebbi",
  "Kogi",
  "Kwara",
  "Lagos",
  "Lagos chapter",
  "Lagos-Ebute Metta",
  "Lagos-Lasuth",
  "Lagos-Luth",
  "LAUTECH",
  "Nasarawa - Keffi",
  "Nasarawa - Lafiya",
  "Niger-Bida",
  "Ogun - Abeokuta",
  "Ogun - Shagamu",
  "Ondo - Owo",
  "ONDO – UNIMEDTH",
  "Osun-Ife",
  "Osun-Osogbo",
  "Oyo",
  "Plateau",
  "Rivers",
  "Sokoto",
  "Taraba",
];

export const globalRegionsData = [
  "The Americas Region",
  "UK/Europe region",
  "Australasia Region",
  "Middle East Region",
  "Africa Region",
];
