import {
  MdMenu,
  MdKeyboardArrowUp,
  MdClose,
  MdLogout,
  MdOutlineSettings,
  MdStore,
  MdMessage,
  MdGroups2,
  MdPlayArrow,
  MdPerson,
  MdAudiotrack,
  MdAddShoppingCart,
  MdShoppingCart,
  MdViewModule,
  MdFilterList,
  MdRefresh,
  MdStorage,
} from "react-icons/md";
import { FiBell, FiDownloadCloud } from "react-icons/fi";
import { HiBadgeCheck, HiDotsVertical, HiOfficeBuilding, HiOutlineHome } from "react-icons/hi";
import {
  FaPlus,
  FaMinus,
  FaCheck,
  FaCheckCircle,
  FaEye,
  FaEyeSlash,
  FaRegCalendarAlt,
  FaCaretDown,
  FaChevronRight,
  FaArrowLeft,
  FaRegNewspaper,
  FaChevronLeft,
  FaCreditCard,
  FaImage,
} from "react-icons/fa";
import { AiOutlineDelete, AiOutlineFileText, AiOutlineLoading3Quarters } from "react-icons/ai";
import {
  BsFileEarmarkImage,
  BsFiletypeDoc,
  BsFiletypePdf,
  BsFillFileEarmarkPdfFill,
  BsPaperclip,
  BsPencil,
  BsSendFill,
  BsSortAlphaDownAlt,
  BsSortAlphaUp,
} from "react-icons/bs";
import { BiBriefcase, BiChevronDown, BiChevronUp, BiLock, BiSortAlt2, BiWorld } from "react-icons/bi";
import { IoList } from "react-icons/io5";
import { RxCounterClockwiseClock } from "react-icons/rx";
import { GoDotFill } from "react-icons/go";
import { MdOutlineBarChart, MdAccessTime } from "react-icons/md";

const icons = {
  bell: <FiBell />,
  download: <FiDownloadCloud />,
  menu: <MdMenu />,
  verticalDots: <HiDotsVertical />,
  plus: <FaPlus />,
  minus: <FaMinus />,
  delete: <AiOutlineDelete />,
  doc: <BsFiletypeDoc />,
  image: <BsFileEarmarkImage />,
  file: <AiOutlineFileText />,
  pdf: <BsFillFileEarmarkPdfFill />,
  pdfAlt: <BsFiletypePdf />,
  check: <FaCheck />,
  checkAlt: <FaCheckCircle />,
  eye: <FaEye />,
  eyeSlash: <FaEyeSlash />,
  sort: <BiSortAlt2 />,
  ascending: <BsSortAlphaUp />,
  descending: <BsSortAlphaDownAlt />,
  arrowUp: <MdKeyboardArrowUp />,
  close: <MdClose />,
  logout: <MdLogout />,
  settings: <MdOutlineSettings />,
  home: <HiOutlineHome />,
  calendar: <FaRegCalendarAlt />,
  store: <MdStore />,
  message: <MdMessage />,
  group: <MdGroups2 />,
  play: <MdPlayArrow />,
  caretDown: <FaCaretDown />,
  person: <MdPerson />,
  chevronRight: <FaChevronRight />,
  chevronLeft: <FaChevronLeft />,
  verified: <HiBadgeCheck />,
  arrowLeft: <FaArrowLeft />,
  audio: <MdAudiotrack />,
  newspaper: <FaRegNewspaper />,
  cart: <MdShoppingCart />,
  cartAdd: <MdAddShoppingCart />,
  pencil: <BsPencil />,
  clockCounter: <RxCounterClockwiseClock />,
  send: <BsSendFill />,
  clip: <BsPaperclip />,
  list: <IoList />,
  grid: <MdViewModule />,
  world: <BiWorld />,
  office: <HiOfficeBuilding />,
  dot: <GoDotFill />,
  chevronDown: <BiChevronDown />,
  chevronUp: <BiChevronUp />,
  briefcase: <BiBriefcase />,
  lock: <BiLock />,
  card: <FaCreditCard />,
  filter: <MdFilterList />,
  refresh: <MdRefresh />,
  reload: <MdRefresh />,
  database: <MdStorage />,
  chart: <MdOutlineBarChart />,
  time: <MdAccessTime />,
  loading: <AiOutlineLoading3Quarters className="animate-spin" />,
  add: <FaPlus />,
  imageIcon: <FaImage />,
};

export default icons;
